### ISSUE TITLE
PCSX crash with Debian Docker image

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#302]
Investigate.
```
cloud-game-gh | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]
cloud-game-gh |
cloud-game-gh | runtime stack:
cloud-game-gh | runtime.throw(0xfc507a, 0x2a)
cloud-game-gh |         /usr/local/go/src/runtime/panic.go:1117 +0x72
cloud-game-gh | runtime.sigpanic()
cloud-game-gh |         /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5
cloud-game-gh |
cloud-game-gh | goroutine 120 [syscall]:
cloud-game-gh | runtime.cgocall(0xd4e8b0, 0xc000285b20, 0xc00008be88)
cloud-game-gh |         /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000285af0 sp=0xc000285ab8 pc=0x45311b
cloud-game-gh | github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch._Cfunc_bridge_retro_run(0x7f635a4e24b0)
cloud-game-gh |         _cgo_gotypes.go:424 +0x3c fp=0xc000285b20 sp=0xc000285af0 pc=0xcc023c
cloud-game-gh | github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch.nanoarchRun.func2()
cloud-game-gh |         /go/src/github.com/giongto35/cloud-game/pkg/emulator/libretro/nanoarch/nanoarch.go:638 +0x54 fp=0xc000285b58 sp=0xc000285b20 pc=0xcc7994
cloud-game-gh | github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch.nanoarchRun()
cloud-game-gh |         /go/src/github.com/giongto35/cloud-game/pkg/emulator/libretro/nanoarch/nanoarch.go:638 +0x3a fp=0xc000285b68 sp=0xc000285b58 pc=0xcc56fa
cloud-game-gh | github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch.(*naEmulator).Start(0xc0002fad80)
cloud-game-gh |         /go/src/github.com/giongto35/cloud-game/pkg/emulator/libretro/nanoarch/naemulator.go:209 +0x105 fp=0xc000285bc0 sp=0xc000285b68 pc=0xcc24a5
cloud-game-gh | github.com/giongto35/cloud-game/v2/pkg/worker/room.NewRoom.func1(0xc0000b8a00, 0xc0004741b0, 0xc0003c1aa0, 0x0, 0x0, 0xc000363a50, 0x7, 0xc000363a57, 0x3, 0xc0004a28c0, ...)
```

**Comment by sergystepanov** [comment]
Just wrong Docker folder mount with the cores folder.
